{
 "title": "PBSPro - hopper - v2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPU Occupation rate (exc. 1-6)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "$B/$A*100", "type": "math" }
   ]
  },
  {
   "title": "NON-AISG Occ. rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "$B/$A*100", "type": "math" }
   ]
  },
  {
   "title": "Total all jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qstat_total_all_jobs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queue - Statistic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,sort_desc(qstat_jobs_in_queue))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(qstat_jobs_by_status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "USER and Total jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,sort_desc(qstat_running_jobs_by_user))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_node_count_free", "legendFormat": "Availiable node" },
    { "expr": "pbs_node_count_offline", "legendFormat": "Offline node" },
    { "expr": "pbs_node_count_down", "legendFormat": "Down nodes" }
   ]
  },
  {
   "title": "GPU Occupation rate (exc. 1-6)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$B/$A*100", "type": "math" }
   ]
  },
  {
   "title": "total running job ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "qstat_jobs_by_status", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "GPU Stat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "sum(pbs_node_gpus_available)", "legendFormat": "Availiable" },
    { "expr": "sum(pbs_node_gpus_total)", "legendFormat": "Total" },
    { "expr": "sum(pbs_node_gpus_used)", "legendFormat": "Use" }
   ]
  },
  { "title": "PBS JOB per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_node_jobs", "legendFormat": "{{node}}" }
   ]
  },
  { "title": "GPU AVAILIBILITY- REALTIME", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_node_gpus_available", "legendFormat": "{{node}}" }
   ]
  },
  { "title": "GPU USAGE HEATMAP - REALTIME", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_node_gpus_used", "legendFormat": "{{node}}" }
   ]
  },
  { "title": "PBS Node status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_node_state", "legendFormat": "{{node}}" }
   ]
  }
 ]
}